# Generated by Django 2.1.5 on 2019-01-31 04:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeatured',
            name='FeaturedItem',
        ),
        migrations.AddField(
            model_name='productfeatured',
            name='FeaturedItem',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='products.ProductFeaturedDetail'),
            preserve_default=False,
        ),
    ]
